# Generated by Django 5.1.2 on 2025-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0003_alter_typeapproval_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='fax_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
