# Generated by Django 5.1.2 on 2025-01-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0004_alter_typeapproval_fax_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeapproval',
            name='alt_email',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='antenna_gain',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='antenna_type',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='emc',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='health_and_safety',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='issue_body',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='product_no',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='software_version',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='technical_variants',
        ),
        migrations.RemoveField(
            model_name='typeapproval',
            name='validity',
        ),
    ]
