# Generated by Django 5.0 on 2025-07-26 00:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealershipLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_options', models.CharField(choices=[('class A', 'CLASS A'), ('class B', 'CLASS B'), ('class C', 'CLASS C'), ('class D', 'CLASS D')], default='Choose your Class', max_length=10)),
                ('equipments', models.CharField(max_length=250)),
                ('reg_company_name', models.CharField(max_length=250)),
                ('reg_trade_name', models.CharField(max_length=250)),
                ('reg_company_num', models.IntegerField()),
                ('tin_num', models.IntegerField()),
                ('incorporation_date', models.DateField()),
                ('commencement_date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('postal_addr', models.CharField(max_length=250)),
                ('gps', models.CharField(max_length=250)),
                ('tele_num', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('site', models.URLField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=250, null=True)),
                ('auth_rep_name', models.CharField(max_length=250)),
                ('auth_rep_tele_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('shareholder_name', models.CharField(max_length=250)),
                ('sharehold', models.IntegerField()),
                ('nationality', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('shareholder_tin_num', models.IntegerField()),
                ('d_name', models.CharField(max_length=250)),
                ('d_nationality', models.CharField(max_length=250)),
                ('d_address', models.CharField(max_length=250)),
                ('d_tin_num', models.IntegerField()),
                ('incorporation_cert', models.FileField(upload_to='dealershipFolder')),
                ('commence_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('share_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('gipc_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('tax_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('ssnit_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('afiliate_cert', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('tech_stuff', models.FileField(upload_to='dealershipFolder')),
                ('company_profile_atch', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('market_plan_atch', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('financial_report_atch', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('bank_receipt', models.FileField(upload_to='dealershipFolder', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('num_employee', models.IntegerField()),
                ('num_employee_props', models.IntegerField()),
                ('oath', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('passport', models.ImageField(upload_to='passports', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png ', 'jpeg', 'jpg'])])),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TypeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('postal_address', models.TextField(max_length=255)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fax_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('alt_email', models.EmailField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('software_version', models.CharField(max_length=100)),
                ('antenna_type', models.CharField(max_length=100)),
                ('antenna_gain', models.CharField(max_length=100)),
                ('technical_variants', models.CharField(max_length=100)),
                ('issue_body', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('validity', models.CharField(max_length=50)),
                ('emc', models.TextField(max_length=255)),
                ('radio', models.TextField(max_length=255)),
                ('health_and_safety', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
