# Generated by Django 5.0 on 2025-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='reg_company_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
