# Generated by Django 5.1.2 on 2025-03-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
