# Generated by Django 5.0 on 2025-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dealershiplicense_reg_company_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='auth_rep_tele_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='d_tin_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='sharehold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='shareholder_tin_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='tele_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='tin_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
