# Generated by Django 5.0 on 2025-07-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dealershiplicense_auth_rep_tele_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
