# Generated by Django 5.1.2 on 2025-03-06 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_typeapproval_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
