# Generated by Django 5.0 on 2025-07-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dealershiplicense_commencement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='num_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='num_employee_props',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
