# Generated by Django 5.0 on 2025-07-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dealershiplicense_num_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
