# Generated by Django 5.0 on 2025-07-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_dealershiplicense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
