# Generated by Django 5.0 on 2025-07-30 16:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_dealershiplicense_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='tele_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
