# Generated by Django 5.1.2 on 2025-03-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_company_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeapproval',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'rejected')], default='submitted', max_length=50),
        ),
    ]
