# Generated by Django 5.1.7 on 2025-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_typeapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
