# Generated by Django 5.0 on 2025-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_dealershiplicense_tele_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='reg_company_num',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='tin_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
