# Generated by Django 5.0 on 2025-07-30 16:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_dealershiplicense_reg_company_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
