# Generated by Django 5.1.7 on 2025-04-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_typeapproval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.OneToOneField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50, on_delete=django.db.models.deletion.CASCADE, to='accounts.typeapproval')),
            ],
        ),
    ]
