# Generated by Django 5.0 on 2025-07-30 16:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dealershiplicense_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='auth_rep_tele_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
