# Generated by Django 5.0 on 2025-07-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_dealershiplicense_auth_rep_tele_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='d_tin_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiplicense',
            name='shareholder_tin_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
