# Generated by Django 5.1.7 on 2025-04-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_approval_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval_status',
        ),
    ]
