# Generated by Django 5.0 on 2025-07-31 01:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_dealershiplicense_d_tin_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplicense',
            name='shareholder_tin_num',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[accounts.models.tin_number_checker]),
        ),
    ]
