# Generated by Django 5.1.2 on 2025-01-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_created=True)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('postal_address', models.TextField(max_length=255)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('phone_no2', models.IntegerField(max_length=10)),
                ('fax_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('alt_email', models.EmailField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_no', models.IntegerField()),
                ('product_no', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('software_version', models.CharField(max_length=100)),
                ('antenna_type', models.CharField(max_length=100)),
                ('antenna_gain', models.CharField(max_length=100)),
                ('technical_variants', models.CharField(max_length=100)),
                ('issue_body', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=50)),
                ('emc', models.TextField(max_length=255)),
                ('radio', models.TextField(max_length=255)),
                ('health_and_safety', models.TextField(max_length=255)),
            ],
        ),
    ]
