# Generated by Django 5.1.2 on 2025-02-23 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0002_alter_typeapproval_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='fax_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='typeapproval',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='typeapproval',
            name='model_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='typeapproval',
            name='product_no',
            field=models.CharField(max_length=50),
        ),
    ]
