# Generated by Django 5.1.2 on 2025-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0003_alter_typeapproval_fax_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
