# Generated by Django 5.0 on 2025-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0004_typeapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typeapproval',
            name='phone_no2',
            field=models.CharField(max_length=10),
        ),
    ]
