# Generated by Django 5.0 on 2025-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0005_alter_typeapproval_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('postal_address', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=50)),
            ],
        ),
    ]
