# Generated by Django 5.0 on 2025-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0006_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapproval',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
